* bookmark-frecency-mode for Emacs
This library exposes ~bookmark-frecency-mode~, which is a global mode that
tracks every visit to a bookmark and sorts bookmarks by frecency, using the
algorithm described in [[https://slack.engineering/a-faster-smarter-quick-switcher/][A faster, smarter Quick Switcher - Slack Engineering]].

The most notable feature of this library is integration with [[https://github.com/emacs-dashboard/emacs-dashboard][dashboard]] package.
With ~bookmark-frecency-mode~, bookmarks in the dashboard widget will be sorted with minimum addition to startup time.
** Installation
This package is not available yet from any of the well-known package registries
such as GNU ELPA, nonGNU ELPA, or MELPA. I may consider submitting this
library as a package once a proper continuous integration is set up.
** Configuration
Turn on ~bookmark-frecency-mode~.

On every visit to a bookmark, the visited bookmark will be updated with the
information needed to calculate the frecency score later.
Thus your bookmarks should be persisted to ~bookmark-file~ at some point after a call to ~bookmark-jump~.
You can customize this behavior by customizing ~bookmark-save-flag~ variable.

If you are using [[https://github.com/emacs-dashboard/emacs-dashboard][dashboard]] package, entries in the bookmark widget will be sorted out of the box once you turn on the global mode.
** Usage
To retrieve a sorted list of bookmarks, you have to use ~bookmark-all-names~.

There is nothing else you have to (or can) do with package. When you turn on ~bookmark-frecency-mode~, every visit to a bookmark will have a side-effect on the bookmark set, and all other libraries using ~bookmark-all-names~ will get a sorted list of bookmarks.
** Acknowledgement
~bookmark-frecency.el~ is inspired by [[https://github.com/alphapapa/frecency.el][frecency.el]] by Adam Porter (a.k.a. alphapapa).
The package is not a dependency of this package because of implementation details.
